# Use the official Ruby 3 Alpine image as the base image
FROM ruby:3.1.4-alpine3.17

# Create a new user and group called 'appuser' with no home directory
RUN addgroup -S appuser && adduser -S appuser -G appuser

# Set the working directory in the container
WORKDIR /home/appuser
RUN chown appuser:appuser /home/appuser


# Install build dependencies, bundle the gems, and remove build dependencies
# RUN apk add --no-cache --virtual .build-deps build-base \
#     && bundle install \
#     && apk del .build-deps
USER appuser

# Copy the Gemfile and Gemfile.lock into the working directory
COPY Gemfile ./
# COPY --chown=appuser:appuser Gemfile Gemfile.lock ./

# Start the application
CMD ["bundle", "install"]
